/*
 * File: app/view/MainView.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MainView', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.MainView',

    requires: [
        'MyApp.view.infoArticleZXDTTab',
        'Ext.tab.Panel',
        'Ext.tab.Tab',
        'Ext.tree.Panel',
        'Ext.tree.View'
    ],

    id: 'myViewPort',
    layout: 'border',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'tabpanel',
                    region: 'center',
                    id: 'htglTabPanelMain',
                    activeTab: 0,
                    items: [
                        {
                            xtype: 'infoArticleZXDTTab'
                        }
                    ],
                    listeners: {
                        show: {
                            fn: me.onHtglTabPanelMainShow,
                            scope: me
                        }
                    }
                },
                {
                    xtype: 'panel',
                    region: 'west',
                    split: true,
                    width: 150,
                    layout: 'accordion',
                    collapsible: true,
                    title: '管理面板',
                    items: [
                        {
                            xtype: 'treepanel',
                            title: '信息检索与统计',
                            root: {
                                expanded: true,
                                children: [
                                    {
                                        id: '',
                                        text: '信息检索设置',
                                        icon: 'images/tubiao.png',
                                        children: [
                                            {
                                                id: 'Crawl',
                                                text: '检索网站设置',
                                                icon: 'images/tubiao.jpg',
                                                leaf: true
                                            },
                                            {
                                                id: 'CrawlInfo',
                                                text: '查看检索信息列表',
                                                icon: 'images/tubiao.jpg',
                                                leaf: true
                                            },
                                            {
                                                id: 'Extract',
                                                text: '字段存储设置',
                                                icon: 'images/tubiao.jpg',
                                                leaf: true
                                            },
                                            {
                                                id: 'Keywords',
                                                text: '查询主题词设置',
                                                icon: 'images/tubiao.jpg',
                                                leaf: true
                                            }
                                        ]
                                    },
                                    {
                                        id: 'ccQueryStatisticsTab',
                                        text: '查询与统计',
                                        icon: 'images/tubiao.png',
                                        leaf: true
                                    }
                                ]
                            },
                            rootVisible: false,
                            viewConfig: {

                            },
                            listeners: {
                                selectionchange: {
                                    fn: me.onTreepanelSelectionChange2,
                                    scope: me
                                }
                            }
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onHtglTabPanelMainShow: function(component, eOpts) {
        Ext.Ajax.request({
            url:'timer_creat_xml'

        });
    },

    onTreepanelSelectionChange2: function(model, selected, eOpts) {
        var xtype = selected[0].get('id');
        //Ext.Msg.alert("",xtype);
        var myTabPanel = Ext.getCmp('htglTabPanelMain');
        //Ext.Msg.alert("",myTabPanel.id);
        myTabPanel.removeAll(true);
        myTabPanel.add(Ext.widget(xtype));
    }

});